name: Create SRC Archive

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Create SRC ZIP
      run: |
        cd src
        zip -r ../src-${{ github.ref_name }}.zip .
        cd ..
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ORG_GH_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./src-${{ github.ref_name }}.zip
        asset_name: src-${{ github.ref_name }}.zip
        asset_content_type: application/zip